swagger: "2.0"
info:
  title: Spitfire Superadmin API
  version: "1.0"

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Enter Bearer token in the format 'Bearer <token>'

security:
  - BearerAuth: [] # Apply BearerAuth security to all endpoints

basePath: "/api/admin"

schemes:
  - http
  - https

paths:
  /shop/all:
    get:
      tags:
        - Shop
      summary: Get information related to all shops
      description: |
        This endpoint retrieves information related to all shops in the system.
        Requires admin authentication.
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              message:
                type: string
                example: "all shops information"
              data:
                type: array
                items:
                  type: object
                  properties:
                    admin_status:
                      type: string
                    createdAt:
                      type: string
                    is_deleted:
                      type: string
                    joined_date:
                      type: string
                    merchant_country:
                      type: string
                    merchant_email:
                      type: string
                    merchant_id:
                      type: string
                    merchant_location:
                      type: string
                    merchant_name:
                      type: string
                    policy_confirmation:
                      type: boolean
                    rating:
                      type: integer
                    restricted:
                      type: string
                    reviewed:
                      type: boolean
                    total_products:
                      type: integer
                    updatedAt:
                      type: string
                    vendor_id:
                      type: string
                    vendor_name:
                      type: string
                    vendor_profile_pic:
                      type: array
                      items:
                        type: string
                    vendor_status:
                      type: string
              total_shops:
                type: integer
                example: 1
              total_banned_shops:
                type: integer
              total_deleted_shops:
                type: integer
              total_pages:
                type: integer
                example: 1
      401:
        description: Unauthorized - Invalid or missing authentication token
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Unauthorized"
            message:
              type: string
              example: "You are not logged in"
      403:
        description: Forbidden - User does not have permission to access the resource
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Forbidden"
            message:
              type: string
              example: "No Permissions to access the requested resource"
      500:
        description: Internal Server Error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Internal Server Error"
            message:
              type: string
              example: "An error occurred while processing the request"
